name: kashef
description: "Kashef - A content safety tool for social media posts."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.6.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^7.0.2
  flutter_riverpod: ^3.1.0
  go_router: ^17.0.1
  dartz: ^0.10.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.9.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^9.0.0
  flutter_native_splash: ^2.4.7
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.4
  local_auth: ^3.0.0
  introduction_screen: ^4.0.0
  image_picker: ^1.2.1
  flutter_dotenv: ^6.0.0
  dio_smart_retry: ^7.0.1
  google_mlkit_text_recognition: ^0.15.0
  lottie: ^3.3.2
  shake: ^3.0.0
  font_awesome_flutter: ^10.12.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/
    - assets/images/
    - assets/team/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_kashef.png"
  adaptive_icon_background: "#0D47A1"
  adaptive_icon_foreground: "assets/images/logo_kashef.png"

flutter_native_splash:
  color: "#0D2E8C"
  image: "assets/images/transparent.png"
  android_12:
    image: "assets/images/transparent.png"
    icon_background_color: "#0D2E8C"


